### ISSUE TITLE
Analysis Lines 180-376 Error

### ISSUE THREAD

**Issue by ThomasRhysEvans** [seanrife/TM-RRR#10]
Running Analysis code chunk lines 180-376 with three lab files to test, the following error is generated:

Error in `$<-.data.frame`(`*tmp*`, "COUNT_DV1_Q1", value = list()) : 
  replacement has 0 rows, data has 132

**Comment by seanrife** [comment]
Thanks Thomas!

Fixed https://github.com/seanrife/TM-RRR/commit/142dc34be8182fe195d73ea9ad2bcee1ed0deab3
