### ISSUE TITLE
Don't format values in results table -- that's a presentation issue not a data issue

### ISSUE THREAD

**Issue by rcalinjageman** [seanrife/TM-RRR#4]
When storing information to your lab results table, you're truncating/formatting values, e.g.:

`  labInfo$ageSD[labInfo$labID == as.factor(lab)] <- format(round(sd(df$Age), digits=2))`

My suggestion would be to store the full values (don't do any formatting).  You can always format/round when the table is presented/printed.  But when you store a truncated value, the other decimal places can't be recovered.  Especially for standard deviations, this can matter when using a summary table like this for a meta-analysis.

**Comment by seanrife** [comment]
Changed. However, I should note that these tables are really for easy importing into the final doc (but it's a good point about separating concerns, etc).
