### ISSUE TITLE
Merging data frames across labs runs into issues with inconsistent column names

### ISSUE THREAD

**Issue by rcalinjageman** [seanrife/TM-RRR#6]
Merging data across labs runs into issues:

` mergedDF <- rbind(mergedDF, df)
`

One issue I've found so far is that the variable groupTime has different numerical suffices (groupTime35, groupTime45, etc.).  I'm not sure if the numerical suffix is needed or not.  If not, this code could remove the numerical suffix prior to merging

`colnames(df)[which(startsWith(names(df), "groupTime"))] <- "groupTime"
`

A second issue is inconsistent number of consent variables.  Not sure if you need these in the merged dataframe.  If not, one easy fix would be to drop all consent-related variables before merging:

`  df <- df[, !(startsWith(names(df), "CONSENT"))] `

**Comment by rcalinjageman** [comment]
Doing some more investigating, there are also merge issues with

- the first column, the id, which has a slightly different name in the ExperimentalPsychologyLab. 
- the groupTime column not being present in the ExperimentalPsychology lab

I've kludged together these fixes, which allows the data to be merged together, but these may or may not be appropriate depending on the meaning of these columns and the goals with the merged data:

The first line removes all the consent columns.
Next, any groupTime columns have their numerical suffix stripped
Then, if there is no groupTime column, it is inserted at the same place (not awesome coding practice)
Finally, *if* the merge table has already been initiated and *if* the first column in df doesn't match what is being used in the merged column, it is set to be the same.  Might be better just to fix the id column in that one lab's data?  Or there might be other strategies for reconciling column names across these different lab data files.


```
  df <- df[, !(startsWith(names(df), "CONSENT"))] 
  
  colnames(df)[which(startsWith(names(df), "groupTime"))] <- "groupTime"
  if(!("groupTime" %in% names(df))) { 
    groupTimecolumn <- which(startsWith(names(mergedDF), "groupTime"))
    df <- data.frame(df[1:groupTimecolumn-1], groupTime = NA, df[groupTimecolumn:ncol(df)])
  }
  if(nrow(mergedDF) > 0) {
  if(colnames(df)[1] != colnames(mergedDF)[1]) {
    colnames(df)[1] <- colnames(mergedDF)[1]
  }
  }
```

**Comment by seanrife** [comment]
Good catch.... Based on the way the survey system records times, I think the most robust way to grab `DelayTime` is to look for the variable `ARTICLETime` and grab the group time immediately before it, as they will always be next to each other. Did this in https://github.com/seanrife/TM-RRR/commit/75dadb6e3f96a8ae009e2a9b3cb1b8fe3fa97e30. I also manually specified the variables we need (see https://github.com/seanrife/TM-RRR/commit/fc0e4e5cb51d706e204ecabf38ce442bc47a8218) as some labs had slightly different structures/groupings, so purging groups of variables seemed like a bad idea (but the var names will always be consistent).
